### ISSUE TITLE
Continuous 403 rate limit error

### ISSUE THREAD

**Issue by samlynndavis** [afragen/git-updater#947]
I've got a number of private repositories that I manage as part of a larger organization's GitHub repo, and I seem to be getting this error _constantly_.

I've gone so far as to create a different access token for every repo that I'm using with this plugin (25 repositories at this point), and I'm still getting this error.

Early on in my use of the plugin, while using it with the same number of repositories, I was able to use the same access token for all of the themes and plugins with no issue, and now I can't seem to get rid of it. I'll wait until the countdown drops from 45 min to 0, and upon refreshing the page or refreshing the cache, it starts right back up.

To provide all the details of my setup, I'm using this plugin on both a production and dev multisite install, but the access tokens used for both are completely different.

Could this have anything to do with needing an enterprise access token, or is there something that I'm doing wrong here?

**Comment by afragen** [comment]
Strange that you would get a timeout error. Authenticated API checks should allow for about 5000 checks per hour instead of the 60 unauthenticated checks per hour. 

GitHub recently changed the format of their access tokens. You might need to reissue them or create new tokens. Refer to the wiki for the correct privileges that you would need.

**Comment by afragen** [comment]
I don't think there is such a thing as a network access token.

**Comment by samlynndavis** [comment]
Hi Andy,

I consulted GitHub support regarding the API issue, and apparently I'm hitting something like 50,000 checks per hour. 

They've provided me with a list of the top 50 URLs being called and the top 3 (with the number of calls added provided at the end of the URL) are:


> https://api.github.com/repos/afragen/github-updater/contents/CHANGES.md?ref=%5BFILTERED%5D - 101743
> https://api.github.com/repos/afragen/github-updater/branches?per_page=100 - 30005
> https://api.github.com/repos/afragen/github-updater/contents/readme.txt?ref=%5BFILTERED%5D - 25634

Along with a host of other URLs related to the plugin. Does this look normal to you at all, or is this a potential bug that should be looked into?

The remaining URLs are all for the various stylesheets and plugin files that I'm watching, but I'm wondering if it's possible to limit the number of calls being made in general, or if it's possible to stop the plugin from checking its own repo at all?

**Comment by afragen** [comment]
It is decidedly not normal. I have seen this once before and tried to get to the bottom of it with GitHub support but we never figured out why it was happening. It's as if something is getting stuck in an object cache and not releasing or not storing data.

The plugin is designed to check the API calls every 12 hours and store the result, if there is no result the API call will repeat to get one. The question then becomes, why is there no result?

I believe there is some caching issue here as otherwise this would affect nearly everyone all the time.

Have you tried turning off the WP-Cron background processing in the settings to see if this can break the cycle?

**Comment by afragen** [comment]
I'm closing in a fix for this. Stay tuned.

**Comment by samlynndavis** [comment]
That would be awesome. I'll keep my eyes peeled. 👌🏾

**Comment by afragen** [comment]
I think I've gotten this fixed in the develop branch. 

I'm caching the API response failure for the period of the rate limit timeout. I currently release the timeout if the access token is set but I may need to rethink how I do that.

**Comment by samlynndavis** [comment]
If I may ask a few more questions here, if my personal access token is set to read: repo and read:packages, should I be using that same one for all private repositories in use, or just for the very first 'GitHub.com Access Token' field?

As it stands, I'm seeing the "Please be patient while WP-Cron finishes making API calls," followed by (at least in the last hour) another ~40+ min rate limit timeout, and red warning icons next to all repositories on my list.

I just wanted to make sure that I'm no doing anything incorrectly here.

Thanks again for all your help. 🙏🏾

**Comment by afragen** [comment]
If all you private repositories are accessible by your user and your user created the access token, you would only need to access token in the GitHub.com field. 

How often does you site/server run WP-Cron?

If you check the setting to bypass WP-Cron, things should just roll along. Warning notices should also surface. 

Testing with the develop branch is going well for me. Are you testing the latest updates to the develop branch?

**Comment by afragen** [comment]
@samlynndavis I just pushed 10.1.0
Please let me know if this fixed the issue for you.
You will still see the timeout notice, but it shouldn't be hammering the API. The API will be hit for 90 seconds after a Refresh Cache, after that, if there are still timeouts, they will be returned from cache and not actual API calls.

**Comment by samlynndavis** [comment]
Hi,

I'm seeing the branch selector finally show up on my theme files, but I haven't been able to switch branches yet.

The error still shows, as you said it would, but checking today just now, I'm getting a 404 error after bypassing the WP-Cron background processing.

This is even after regenerating my access token and pasting into only the Github.com Access Token field.

**Comment by samlynndavis** [comment]
@afragen to give a little more context, I've installed a trial version of the PRO version to sit on top of the base git-updater plugin. I've noticed that the most recent plugin update contains a "github-updater" php file that is missing a plugin URI, but I'm not sure if that's by design or not.

I did a quick issue search and found that a previous user's 404 error was resolved by a plugin not having the proper URI in the header, so perhaps this is my issue here?

**Comment by samlynndavis** [comment]
Sorry, one further update: It looks like the branch switching does work for the git-updater plugin, but not PRO (I'm guessing because this is a private repo?), as well working for a couple of other plugins that I've got installed that are held in public repositories.

**Comment by afragen** [comment]
The extra github-updater.php is by design. It's there for people updating from the old version. 

Branch switching is a premium feature and requires Git Updater PRO. 

Yes, Git Updater PRO is in a private repo so you won't be able to branch switch, etc. I'm fixing the issue where Git Updater PRO shows a warning icon. You can ignore it for now. 

Are you having the any more timeout issues?

**Comment by samlynndavis** [comment]
I'm still seeing the below.

![Screen Shot 2021-06-01 at 10 33 23 AM](https://user-images.githubusercontent.com/5041869/120351601-a0f9bf80-c2c5-11eb-9b87-7a17dc77f6e0.png)

And as I'm running Git Updater PRO right now, I have access to the branch switching feature, but am seeing this at the moment despite have the GitHub URIs present in my header:

![Screen Shot 2021-06-01 at 10 47 22 AM](https://user-images.githubusercontent.com/5041869/120353619-6b55d600-c2c7-11eb-9e3e-86a0919d1351.png)

So, the timeout message still shows, and seems to reset every time the counter drops to 0.

**Comment by afragen** [comment]
Which repo is not getting updates?

Also does QM report actual outgoing HTTP requests? With the update in Git Updater 10.1.0 it should only do an HTTP request hourly. The goal was to stop the continuous requests.

**Comment by samlynndavis** [comment]
Hey Andy,

After finally realizing what QM was referring to, I installed the plugin and I'm seeing this for all repositories...

![Screen Shot 2021-06-03 at 1 36 15 PM](https://user-images.githubusercontent.com/5041869/120695447-0342f380-c471-11eb-809b-87b665435ce3.png)

Does it make sense that it's appened that /content/ to the url?

**Comment by afragen** [comment]
Those HTTP GET requests are correct. The 404 error means there's an authentication issue.

Git Updater 10.2.x should fix the 404 issues with the Git Updater PRO plugin.

You might try creating a new personal access token and re-saving. https://git-updater.com/knowledge-base/general-usage/

**Comment by samlynndavis** [comment]
I'm still trying to dig into this -- I may ping GitHub support again -- as I've regenerated the token and then completely deleted and created a new one, and I'm still getting this 404 error.

I'm not sure if there's a limit to the number of times that I can generate and regenerate access tokens before my account is flagged or something (though my other access tokens seem to be working), but it's still throwing that error my way.

**Comment by afragen** [comment]
You might try that part about creating the access token from the account that owns the repos. I do know that I have been given access to other user's repositories but I think that may be on a per repository basis.

**Comment by afragen** [comment]
It would seem a better idea for the repository owner to create a personal access token and distribute these tokens as needed. Also, rescind here tokens as necessary.

**Comment by afragen** [comment]
@samlynndavis Make sure you update to latest versions of both Git Updater and Git Updater PRO. I've done a lot lately to be able to _ignore_ specific repositories. In this case ignore Git Updater PRO from hitting the GitHub API.

**Comment by afragen** [comment]
This should be fixed as these errors from the API are cached and the cached values returned instead of continually querying the API.

The cache is saved in a similar manner to other cached values, for 12 hours, and can be flushed with the Refresh Cache button.

If this is still an issue please re-open.

**Comment by MSEGitHub** [comment]
@afragen I have started to see this issue over the past few weeks. We've been slowly upgrading from the old github-updater to the git-updater and recently I started getting timeouts. Because of the timing I downgraded the 10.6.x sites we had to 10.5.2 to see if it would stop but it hasn't.

When I reached out to GitHub about the issue they said these were the top URL's hit by the API:
![image](https://user-images.githubusercontent.com/63716480/140044885-feb2ed74-8504-4c82-adbd-82d6cc3ecccd.png)

Any thoughts?

The one change we did make was with github-updater I used to select bypass WP-CRON but with the new version i have been deselecting it. And there is still a mix between old and new.

**Comment by MSERobert** [comment]
@afragen I have started to see this issue over the past few weeks. We've been slowly upgrading from the old github-updater to the git-updater and recently I started getting timeouts. Because of the timing I downgraded the 10.6.x sites we had to 10.5.2 to see if it would stop but it hasn't.

When I reached out to GitHub about the issue they said these were the top URL's hit by the API:
![image](https://user-images.githubusercontent.com/63716480/140044885-feb2ed74-8504-4c82-adbd-82d6cc3ecccd.png)

Any thoughts?

The one change we did make was with github-updater I used to select bypass WP-CRON but with the new version i have been deselecting it. And there is still a mix between old and new.

**Comment by afragen** [comment]
Take a look at https://git-updater.com/knowledge-base/troubleshooting/

Let me know if Query Monitor shows any HTTP errors.

**Comment by afragen** [comment]
There shouldn't be anything sensitive in the URL being looked at. If there is something is being added on that might be incorrect. 

Can you screenshot any errors in the Git Updater settings page and any HTTP errors. You might need to bypass WP-Cron to see these errors.

**Comment by afragen** [comment]
@MSERobert please make sure you are using the latest version of Git Updater.

**Comment by MSERobert** [comment]
@afragen I re-upgraded the clients back to the latest. I also came across what you wrote in this thread:

> If all you private repositories are accessible by your user and your user created the access token, you would only need to access token in the GitHub.com field.
> 

I was also under the impression I needed an individual entry for each private repository plugin when using the "gu_set_options" filter. Could doing this cause the excessive hits?  

I have since removed the extra entries and did not see an error overnight. I will see how it goes today.

**Comment by afragen** [comment]
I wonder whether one of the entries you deleted had a typo and therefore an authentication error.

**Comment by MSERobert** [comment]
I double-checked the entries but I couldn't find any typos. So far it's been over 24 hours without a single error. I'm reaching out to GitHub to see how far below the threshold I am now.

**Comment by afragen** [comment]
You can use `curl` to hit an endpoint and it will show you the number of calls that remain in the rate limit. 

https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api

**Comment by MSERobert** [comment]
Thanks for that, I caught it right before it reset for the hour and it had 1309 calls, definitely a lot better.
